# Supabase Configuration for TailTracker
# This file configures the local Supabase development environment

[api]
enabled = true
port = 54321
schemas = ["public", "auth", "realtime", "storage"]
extra_search_path = ["public", "auth"]
max_rows = 1000

[auth]
enabled = true
port = 54322
external_url = "http://localhost:54321"
jwt_expiry = 3600
jwt_secret = "your-jwt-secret-here"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54323
shadow_port = 54324
major_version = 15

[storage]
enabled = true
port = 54325
file_size_limit = "50MB"
buckets = [
  { name = "pet-photos", public = true },
  { name = "documents", public = false },
  { name = "qr-codes", public = true }
]

[edge_functions]
enabled = true
port = 54326

[analytics]
enabled = false

[studio]
enabled = true
port = 54323

[project_id] 
value = "tkcajpwdlsavqfqhdawy"