# Supabase Configuration for TailTracker
# This file configures the local Supabase development environment

project_id = "tkcajpwdlsavqfqhdawy"

[api]
enabled = true
port = 54321
schemas = ["public", "auth", "realtime", "storage"]
extra_search_path = ["public", "auth"]
max_rows = 1000

[auth]
enabled = true
jwt_expiry = 3600
jwt_secret = "your-jwt-secret-here"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54323
shadow_port = 54324
major_version = 15

[studio]
enabled = true
port = 54323