# TailTracker Pet Wellness Platform - Supabase Configuration
# Comprehensive health and care management system (GPS tracking removed)

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 10000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

# Database configuration for wellness platform
[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"
default_pool_size = 25
max_client_conn = 200

# Essential extensions for wellness platform (NO PostGIS - GPS removed)
[db.extensions]
# Core PostgreSQL extensions
uuid-ossp = "1.1"
pg_trgm = "1.6"
btree_gin = "1.3"
pg_stat_statements = "1.10"

# Time-series analysis for health metrics
timescaledb = "2.11.2"

# Full-text search for medical records
pg_stat_statements = "1.10"

# Analytics and reporting
pg_cron = "1.6"

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = false

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://tailtracker.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

# Authentication providers for wellness platform
[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
redirect_uri = ""

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.zoom]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

# Email templates for wellness notifications
[auth.email.invite]
subject = "You've been invited to join a pet family on TailTracker"
template = """
<h2>You've been invited to help care for a beloved pet!</h2>
<p>Someone has invited you to join their pet family on TailTracker, the comprehensive pet wellness platform.</p>
<p>Click the link below to accept the invitation and start helping with pet care coordination:</p>
<p><a href="{{ .ConfirmationURL }}">Accept Invitation</a></p>
<p>TailTracker helps families:</p>
<ul>
  <li>Track pet health metrics and wellness</li>
  <li>Coordinate care tasks and schedules</li>
  <li>Share medical records and updates</li>
  <li>Receive preventive care reminders</li>
  <li>Manage emergency protocols</li>
</ul>
<p>Join us in providing the best care for our furry family members!</p>
"""

[auth.email.confirmation]
subject = "Welcome to TailTracker - Confirm your email"
template = """
<h2>Welcome to TailTracker!</h2>
<p>Thank you for joining TailTracker, the comprehensive pet wellness and care management platform.</p>
<p>Please confirm your email address by clicking the link below:</p>
<p><a href="{{ .ConfirmationURL }}">Confirm Email Address</a></p>
<p>Once confirmed, you can:</p>
<ul>
  <li>Create pet profiles with comprehensive health records</li>
  <li>Track health metrics and behavioral patterns</li>
  <li>Coordinate care tasks with family members</li>
  <li>Receive wellness insights and recommendations</li>
  <li>Set up emergency protocols for your pets</li>
</ul>
<p>Welcome to better pet care!</p>
"""

[auth.email.recovery]
subject = "TailTracker - Reset your password"
template = """
<h2>Reset your TailTracker password</h2>
<p>We received a request to reset your password for your TailTracker account.</p>
<p>Click the link below to create a new password:</p>
<p><a href="{{ .ConfirmationURL }}">Reset Password</a></p>
<p>If you didn't request this password reset, you can safely ignore this email.</p>
<p>Your pets are counting on you!</p>
"""

[auth.email.change]
subject = "TailTracker - Confirm your new email address"
template = """
<h2>Confirm your new email address</h2>
<p>Please confirm your new email address for your TailTracker account:</p>
<p><a href="{{ .ConfirmationURL }}">Confirm New Email</a></p>
<p>This ensures you continue receiving important pet care notifications and updates.</p>
"""

# Edge Functions configuration for wellness platform
[edge-runtime]
enabled = true
policy = "permissive"
inspector_port = 8083

# Analytics configuration
[analytics]
enabled = true
port = 54327
vector_port = 54328
# Replace with your Google Analytics ID for wellness platform
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = "supabase/gcp.json"

# Realtime configuration for family coordination
[realtime]
enabled = true
ip_version = "ipv4"
db_host = "localhost"
db_port = 54322
db_user = "supabase_admin"
db_password = "postgres"
db_name = "postgres"
api_jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"
secret_key_base = "UpNVntn3cDxHJpq99YMc1T1AQgQpc8kfYTuRgBiYa15BLrx8en4CpDc9cm8kdkUK"
max_header_length = 4096
pool_size = 10

# Realtime rate limiting for wellness notifications
[realtime.tenant_rate_limiter]
enabled = true
rate = 100
burst = 200

# Studio configuration
[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"